---

- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"

  tasks:
    - import_tasks: tasks/auth.yml

    - name: Check if dev project exists
      command: >-
        oc get project
        {{ dev_project_name }}
        --output json
        --config "{{ local_kubeconfig }}"
      environment: "{{ openshift_local.env }}"
      register: check_dev_project_exists
      changed_when: no
      failed_when: no

    - name: Create dev project
      shell: >-
        oc new-project
        {{ dev_project_name }}
        --config "{{ local_kubeconfig }}"
      environment: "{{ openshift_local.env }}"
      when: check_dev_project_exists.rc != 0

    - name: Give {{ demo_user }} access to dev project
      command: >-
        oc policy
        add-role-to-user
        edit
        {{ demo_user }}
        --namespace {{ dev_project_name }}
        --config "{{ local_kubeconfig }}"
      environment: "{{ openshift_local.env }}"

    - name: Pause for the dev project to finish creating
      pause:
        seconds: 5
      when: check_dev_project_exists.rc != 0

    - name: Check if demo app exists in dev project
      command: >-
        oc get service
        {{ app_name }}
        --output json
        --namespace {{ dev_project_name }}
        --config "{{ local_kubeconfig }}"
      environment: "{{ openshift_local.env }}"
      register: check_dev_demo_app_exists
      changed_when: no
      failed_when: no

    - name: Deploy demo app to the dev project
      shell: >-
        oc process
        --filename "{{ playbook_dir }}/files/demo_app_dev.yml"
        --param NAME={{ app_name }}
        --param SOURCE_REPOSITORY_URL=https://github.com/jaredhocutt/openshift-guestbook.git
        --labels app={{ app_name }}
        --local
        | oc apply --config "{{ local_kubeconfig }}" -f - --namespace {{ dev_project_name }}
      environment: "{{ openshift_local.env }}"
      register: process_demo_app_template_dev
      when: check_dev_demo_app_exists.rc != 0

    - name: Wait until the demo app deployment is complete
      command: >-
        oc get deploymentconfig
        {{ app_name }}
        --output json
        --namespace {{ dev_project_name }}
        --config "{{ local_kubeconfig }}"
      environment: "{{ openshift_local.env }}"
      register: wait_dev_demo_app_deployed
      until: (wait_dev_demo_app_deployed.stdout | from_json)['status']['availableReplicas'] > 0
      delay: 5
      retries: 75
      changed_when: no
