---

- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"

  tasks:
    - import_tasks: tasks/auth.yml

    - name: Create external route for the registry
      k8s:
        namespace: default
        definition:
          apiVersion: v1
          kind: Route
          metadata:
            name: docker-registry-external
          spec:
            host: registry.{{ openshift_local.apps_subdomain }}
            port:
              targetPort: 5000-tcp
            tls:
              termination: reencrypt
            to:
              kind: Service
              name: docker-registry
              weight: 100
        state: present
      environment: "{{ openshift_local.env }}"
