
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    dev_project_name: demo-app-dev
    prod_project_name: demo-app-prod

  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"

  tasks:
    - import_tasks: tasks/auth.yml

    - name: Delete local cluster projects
      k8s:
        api_version: v1
        kind: Project
        name: "{{ item }}"
        state: absent
      environment: "{{ openshift_local.env }}"
      loop:
        - "{{ dev_project_name }}"
        - "{{ prod_project_name }}"

    - name: Delete cloud cluster projects
      k8s:
        api_version: v1
        kind: Project
        name: "{{ item }}"
        state: absent
      environment: "{{ openshift_cloud.env }}"
      loop:
        - "{{ dev_project_name }}"
        - "{{ prod_project_name }}"

    - name: Delete kubeconfig files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ local_kubeconfig }}"
        - "{{ cloud_kubeconfig }}"
